#!/bin/bash

#name=$(basename $0)
#if [ $name = "addem" ] 
#then 
#  total=$[ $1 + $2 ]
#  echo "计算值为 $1 + $2 = $total"
#elif [ $name = "multen" ]
#then
#  total=$[ $1 * $2  ]
#  echo "计算值为 $1 * $2 = $total"
#fi


#加强版
#name=$(basename $0)
#if [ -z "$1" -o  -z $2 ]	#-z $1 检查$1的长度是否为0，如果为0执行then中的命令，如果不为0执行else中的命令， -z $2一样， -o 是或者，如果$1或者$2其中1个长度为0那么就执行then中的命令
#then
#  echo "没有按照要求输入两个变量，请重新执行脚本"
#  exit 1
#else
#  if [ $name = "addem" ]
#  then
#    total=$[ $1 + $2 ]
#    echo "计算值为 $1 + $2 = $total"
#  elif [ $name = "multen" ]
#  then
#    total=$[ $1 * $2  ]
#    echo "计算值为 $1 * $2 = $total"
#  fi
#fi


#提升加强版
name=$(basename $0)

if [ $# -ne 2 ]
then 
echo "没有按照要求输入两个变量，请重新执行脚本时 跟上两个变量"
exit 1
else
  if [ $name = "addem" ]
  then
    total=$[ $1 + $2 ]
    echo "执行的是 $name 这个脚本，这个脚本返回的值是 $1 + $2 =$total "
  elif [ $name = "multen" ]
  then
    total=$[ $1 * $2 ]
    echo "执行的是 $name 这个脚本，这个脚本返回的值是 $1 * $2 =$total "
  fi
fi

